import = [
	"~/.config/alacritty/aura.toml"
]

[env]
TREM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
dynamic_padding = true

decorations = "none"

opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 10

[keyboard]
bindings = [
  { key = "T", mods = "Control|Shift", action = "SpawnNewInstance" }
]
